name: Set OpenAI API Key for Binder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set OpenAI API Key in .env
      run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

    - name: Commit and push .env file to GitHub
      run: git add .env && git commit -m "Add OpenAI API key" && git push
